<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
        version="2.0"
        xmlns:dita-ot="http://dita-ot.sourceforge.net/ns/201007/dita-ot"
        xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
        xmlns:whc="http://www.oxygenxml.com/webhelp/components">

    <xsl:param name="tocNumbering" select="'true'"/>
    <xsl:param name="using_transtype"/>

    <!--Template for adding custom footer -->
    <xsl:template match="whc:include_html[@href='footer.xml']" mode="copy_template create-tiles">
        <xsl:choose>
            <xsl:when test="$using_transtype = 'ia-webhelp-responsive-YB'">
                <footer class="navbar navbar-default wh_footer" whc:version="21.0">
                    <div class=" footer-container mx-auto " id="custom_footer">

                        Generated by
                        <a class="oxyFooter" href="https://intelliarts.com/" target="_blank">
                            Yuliia Bondarenko
                        </a>
                    </div>
                </footer>
            </xsl:when>
            <xsl:otherwise>
                <xsl:next-match/>
            </xsl:otherwise>
        </xsl:choose>
    </xsl:template>

</xsl:stylesheet>